name: flutter_rsa
description: RSA Encryption
version: 1.1.1
repository: https://github.com/ToxicAura60/flutter_rsa

environment:
  sdk: ^3.6.0

dependencies:
  pointycastle: ^3.9.1
  asn1lib: ^1.5.8

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
